services:
  dev-db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres-db
    ports:
      - 5434:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3

  backend:
    build: ./backend
    container_name: shop-co-backend
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@dev-db:5432/postgres-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres-db
      - JWT_SECRET=my_password_very_very
      - NODE_ENV=development
    ports:
      - "3005:3005"
    depends_on:
      dev-db:
        condition: service_healthy # Wait for MySQL to pass healthcheck
    volumes:
      - ./backend:/app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: shop-co-frontend
    environment:
      - NODE_ENV=development
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    command: npm run dev # Launches Vite development server

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
